services: 
  valheim: 
    image: ghcr.io/lloesche/valheim-server:latest
    cap_add:
      - sys_nice
    volumes: 
      - /mnt/ebs_volume/valheim-server/config:/config
      - /mnt/ebs_volume/valheim-server/data:/opt/valheim
    ports: 
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
    env_file:
      - /mnt/ebs_volume/valheim-server/valheim.env
    environment:
      - DISCORD_WEBHOOK=https://discord.com/api/webhooks/1223128455877496932/s2Eebpx6uMugV4SUHImQGKHV64CxC97SHrN3c9sg78S9GQ0KGSikJ8f9Fl40Z0trRsNj
      - DISCORD_BOOT_MESSAGE=Starting up Valheim server $$SERVER_NAME
      - DISCORD_PRESTART_MESSAGE=Valheim server - $$SERVER_NAME has almost started
      - DISCORD_PRESHUTDOWN_MESSAGE=Valheim server - $$SERVER_NAME is beginning to shutdown
      - DISCORD_SHUTDOWN_MESSAGE=Valheim server - $$SERVER_NAME has shutdown
      - 'PRE_BOOTSTRAP_HOOK=curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$$(eval echo $$DISCORD_BOOT_MESSAGE)\"}" "$$DISCORD_WEBHOOK"'
      - 'PRE_SERVER_RUN_HOOK=curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$$(eval echo $$DISCORD_PRESTART_MESSAGE)\"}" "$$DISCORD_WEBHOOK"'
      - 'PRE_SERVER_SHUTDOWN_HOOK=curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$$(eval echo $$DISCORD_PRESHUTDOWN_MESSAGE)\"}" "$$DISCORD_WEBHOOK"'
      - 'POST_SERVER_SHUTDOWN_HOOK=curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$$(eval echo $$DISCORD_SHUTDOWN_MESSAGE)\"}" "$$DISCORD_WEBHOOK"'
    restart: always
    stop_grace_period: 2m