version: "3"

services: 
  valheim: 
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - /mnt/ebs_volume/valheim-server/config:/config
      - /mnt/ebs_volume/valheim-server/data:/opt/valheim
    ports: 
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
    env_file:
      - /mnt/ebs_volume/valheim-server/valheim.env
    restart: always
    stop_grace_period: 2m